server:
  port: 9982
spring:
  application:
    name: business-biz-service
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
        namespace: manage-biz
        username: manage-biz
        password: manage-biz
